#!/bin/bash

VIMRC="$TMPDIR/mini-vimrc"
SOURCE="$HOME/.vim/bundle/vim-textobj-quote"

cat > $VIMRC << EOF
set nocompatible
syntax on
set shortmess+=I

for dep in ['vader.vim', 'vim-textobj-user']
  execute 'set rtp+=' . finddir(dep, expand('~/.vim').'/**')
endfor
set rtp+=$SOURCE
EOF

cd $SOURCE/test
vim -u $VIMRC +Vader*
#vim -u $VIMRC '+Vader!*' && echo Success || echo Failure

rm -f $VIMRC
