# Vuetify all color classes
color_classes = ["red", "pink", "purple", "deep-purple", "indigo", "blue", "light-blue", "cyan", "teal", "green", "light-green", "lime", "yellow", "amber", "orange", "deep-orange", "brown", "blue-grey", "grey","black","white","transparent","red lighten-5","red lighten-4","red lighten-3","red lighten-2","red lighten-1","red darken-1","red darken-2","red darken-3","red darken-4","red accent-1","red accent-2","red accent-3","red accent-4","pink lighten-5","pink lighten-4","pink lighten-3","pink lighten-2","pink lighten-1","pink darken-1","pink darken-2","pink darken-3","pink darken-4","pink accent-1","pink accent-2","pink accent-3","pink accent-4","purple lighten-5","purple lighten-4","purple lighten-3","purple lighten-2","purple lighten-1","purple darken-1","purple darken-2","purple darken-3","purple darken-4","purple accent-1","purple accent-2","purple accent-3","purple accent-4","deep-purple lighten-5","deep-purple lighten-4","deep-purple lighten-3","deep-purple lighten-2","deep-purple lighten-1","deep-purple darken-1","deep-purple darken-2","deep-purple darken-3","deep-purple darken-4","deep-purple accent-1","deep-purple accent-2","deep-purple accent-3","deep-purple accent-4","indigo lighten-5","indigo lighten-4","indigo lighten-3","indigo lighten-2","indigo lighten-1","indigo darken-1","indigo darken-2","indigo darken-3","indigo darken-4","indigo accent-1","indigo accent-2","indigo accent-3","indigo accent-4","blue lighten-5","blue lighten-4","blue lighten-3","blue lighten-2","blue lighten-1","blue darken-1","blue darken-2","blue darken-3","blue darken-4","blue accent-1","blue accent-2","blue accent-3","blue accent-4","light-blue lighten-5","light-blue lighten-4","light-blue lighten-3","light-blue lighten-2","light-blue lighten-1","light-blue darken-1","light-blue darken-2","light-blue darken-3","light-blue darken-4","light-blue accent-1","light-blue accent-2","light-blue accent-3","light-blue accent-4","cyan lighten-5","cyan lighten-4","cyan lighten-3","cyan lighten-2","cyan lighten-1","cyan darken-1","cyan darken-2","cyan darken-3","cyan darken-4","cyan accent-1","cyan accent-2","cyan accent-3","cyan accent-4","teal lighten-5","teal lighten-4","teal lighten-3","teal lighten-2","teal lighten-1","teal darken-1","teal darken-2","teal darken-3","teal darken-4","teal accent-1","teal accent-2","teal accent-3","teal accent-4","green lighten-5","green lighten-4","green lighten-3","green lighten-2","green lighten-1","green darken-1","green darken-2","green darken-3","green darken-4","green accent-1","green accent-2","green accent-3","green accent-4","light-green lighten-5","light-green lighten-4","light-green lighten-3","light-green lighten-2","light-green lighten-1","light-green darken-1","light-green darken-2","light-green darken-3","light-green darken-4","light-green accent-1","light-green accent-2","light-green accent-3","light-green accent-4","lime lighten-5","lime lighten-4","lime lighten-3","lime lighten-2","lime lighten-1","lime darken-1","lime darken-2","lime darken-3","lime darken-4","lime accent-1","lime accent-2","lime accent-3","lime accent-4","yellow lighten-5","yellow lighten-4","yellow lighten-3","yellow lighten-2","yellow lighten-1","yellow darken-1","yellow darken-2","yellow darken-3","yellow darken-4","yellow accent-1","yellow accent-2","yellow accent-3","yellow accent-4","amber lighten-5","amber lighten-4","amber lighten-3","amber lighten-2","amber lighten-1","amber darken-1","amber darken-2","amber darken-3","amber darken-4","amber accent-1","amber accent-2","amber accent-3","amber accent-4","orange lighten-5","orange lighten-4","orange lighten-3","orange lighten-2","orange lighten-1","orange darken-1","orange darken-2","orange darken-3","orange darken-4","orange accent-1","orange accent-2","orange accent-3","orange accent-4","deep-orange lighten-5","deep-orange lighten-4","deep-orange lighten-3","deep-orange lighten-2","deep-orange lighten-1","deep-orange darken-1","deep-orange darken-2","deep-orange darken-3","deep-orange darken-4","deep-orange accent-1","deep-orange accent-2","deep-orange accent-3","deep-orange accent-4","brown lighten-5","brown lighten-4","brown lighten-3","brown lighten-2","brown lighten-1","brown darken-1","brown darken-2","brown darken-3","brown darken-4","blue-grey lighten-5","blue-grey lighten-4","blue-grey lighten-3","blue-grey lighten-2","blue-grey lighten-1","blue-grey darken-1","blue-grey darken-2","blue-grey darken-3","blue-grey darken-4","grey lighten-5","grey lighten-4","grey lighten-3","grey lighten-2","grey lighten-1","grey darken-1","grey darken-2","grey darken-3","grey darken-4","lighten-5","lighten-4","lighten-3","lighten-2","lighten-1","darken-1","darken-2","darken-3","darken-4","accent-1","accent-2","accent-3","accent-4"]

components = [
  ("v-container\tContainer component - Vuetify", "v-container>\n  $2\n</v-container>$0"),
  ("v-layout\tLayout component - Vuetify", "v-layout row wrap>\n  $1\n</v-layout>$0"),
  ("v-flex\tFlex component - Vuetify", "v-flex ${1:xs1}>\n  $2\n</v-flex>$0"),
  ("v-spacer\tSpacer component - Vuetify", "v-spacer></v-spacer>$0"),
  ("v-alert\tAlert component - Vuetify", "v-alert type=\"${1:primary}\" :value=\"${2:true}\">\n\t$3\n</v-alert>$0"),
  ("v-avatar\tAvatar component - Vuetify", "v-avatar\n  size=\"${1:avatarSize}\"\n  color=\"${2:primary}\"\n>\n  <img src=\"${3:src}\" alt=\"${4:alt}\">\n</v-avatar>$0"),
  ("v-badge\tBadge component - Vuetify", "v-badge ${1:left} ${2:color=\"${3:primary}\"}>\n  <span slot=\"badge\">${4:badgeText}</span> <!--slot can be any component-->\n  <v-icon ${5:large} color=\"${6:primary}\">${7:icon}</v-icon>\n</v-badge>$0"),    
  ("v-bottom-nav\tBottom Nav component - Vuetify", "v-bottom-nav\n  ${1:absolute}\n  ${2:value=\"${3:value}\"}\n  ${4:active.sync=\"${5:value}\"}\n  ${6:shift}\n  ${7:color=\"${8:primary}\"}\n>\n<v-btn ${9:flat} ${10:color=\"${11:primary}\"} ${12:dark}>\n  <span>${13:text}</span>\n  <v-icon>${14:icon}</v-icon>\n</v-btn>$15\n</v-bottom-nav>$0"),    
  ("v-bottom-sheet\tBottom Sheet component - Vuetify", "v-bottom-sheet ${1:inset} ${2:v-model=\"${3:value}\"}>\n  $4\n</v-bottom-sheet>$0"),
  ("v-breadcrumbs-item\tBreadcrumbs Item component - Vuetify", "v-breadcrumbs-item>\n  ${1:text}\n</v-breadcrumbs-item>$0"),
  ("v-btn\tBtn component - Vuetify", "v-btn color=\"${1:success}\">${2:text}</v-btn>"),
  ("v-speed-dial\tSpeed Dial component - Vuetify", "v-speed-dial\n  ${1:bottom} ${2:top}\n  ${3:left} ${4:right}\n  ${5:direction=\"${6:top}\"}\n  ${7:open-on-hover}\n  ${8:transition=\"${9:fade-transition}\"}\n>\n  $10\n</v-speed-dial>$0"),
  ("v-card\tCard component - Vuetify", "v-card>\n  $1\n</v-card>$0"),
  ("v-card-media\tCard Media component - Vuetify", "v-card-media\n  ${1:contain}\n  ${2:height=\"${3:auto}\"}\n  ${4:src=\"${5:src}\"}\n>\n\t$6\n</v-card-media>$0"),
  ("v-card-title\tCard Title component - Vuetify", "v-card-title ${1:primary-title}>\n  ${2:title}\n</v-card-title>$0"),
  ("v-card-actions\tCard Actions component - Vuetify", "v-card-actions>\n  $1\n</v-card-actions>$0"),
  ("v-card-text\tCard Text component - Vuetify", "v-card-text>\n  $1\n</v-card-text>$0"),
  ("v-carousel\tCarousel component - Vuetify", "v-carousel ${1:hide-controls}>\n  $2\n<v-carousel>$0"),
  ("v-carousel-item\tCarousel Item component - Vuetify", "v-carousel-item\n  ${1:src=\"${2:src}\"}\n></v-carousel-item>$0"),
  ("v-data-iterator\tData Iterator component - Vuetify", "v-data-iterator\n  content-tag=\"${1:tag}\"\n  ${2:row}\n  ${3:wrap}\n  items=\"${4:items}\"\n  rows-per-page-items=\"${5:rowsPerPageItems}\"\n  pagination.sync=\"${6:pagination}\"\n>\n  $7\n</v-data-iterator>$0"),
  ("v-data-table\tData Table component - Vuetify", "v-data-table\n  ${1:headers=\"${2:headers}\"}\n  ${3:items=\"${4:items}\"}\n  ${5:hide-actions}\n  ${6:class=\"${7:elevation-1}\"}\n  ${8:select-all}\n  ${9:pagination.sync=\"${10:pagination}\"}\n  ${11:item-key=\"${12:id}\"}\n  ${13:loading=\"${14:true}\"}\n  ${15:search=\"${17:search}\"}\n>\n  $18\n</v-data-table>$0"),
  ("v-edit-dialog\tEdit Dialog component - Vuetify", "v-edit-dialog\n  return-value=\"${1:returnValue}\"\n  ${2:large} cancel-text=\"${3:Cancel}\" save-text=\"${4:Save}\"\n  ${5:lazy}\n  ${6:persistent}\n  transition=\"${7:fade-transition}\"\n> ${8:text}$9\n  <v-text-field\n    slot=\"input\"\n    label=\"${10:value}\"\n    v-model=\"${11:value}\"\n    ${12:single-line}\n    ${13:counter}\n    rules=\"${14:rules}\"\n  ></v-text-field>$15\n</v-edit-dialog>$0"),
  ("v-dialog\tDialog component - Vuetify", "v-dialog\n  v-model=\"${1:dialog}\"\n  ${2:scrollable} ${3:fullscreen} \n  ${4:persistent} ${5::overlay=\"${6:false}\"}\n  ${7:max-width=\"${8:500px}\"}\n  ${9:transition=\"${10:dialog-transition}\"}\n>\n  $11\n</v-dialog>$0"),
  ("v-divider\tDivider component - Vuetify", "v-divider>$1</v-divider>$0"),
  ("v-expansion-panel\tExpansion Panel component - Vuetify", "v-expansion-panel ${1:expand} ${2:focusable}>\n  $3\n</v-expansion-panel>$0"),
  ("v-expansion-panel-content\tExpansion Panel Content component - Vuetify", "v-expansion-panel-content\n  <div slot=\"header\">Item</div>\n  $1\n</v-expansion-panel-content>$0"),
  ("v-footer\tFooter component - Vuetify", "v-footer>\n  $1\n</v-footer>"),
  ("v-form\tForm component - Vuetify", "v-form>\n  $1\n</v-form>$0"),
  ("v-select\tSelect component - Vuetify", "v-select\n  :items=\"${1:items}\"\n  v-model=\"${2:value}\"\n  label=\"${3:label}\"\n></v-select>$0"),
  ("v-radio-group\tRadio Group component - Vuetify", "v-radio-group v-model=\"${1:value}\">\n  $1\n</v-radio-group>$0"),
  ("v-radio\tRadio component - Vuetify", "v-radio label=\"${1:label}\" value=\"${2:value}\"></v-radio>$0"),
  ("v-checkbox\tCheckbox component - Vuetify", "v-checkbox label=\"${1:label}\" v-model=\"${2:value}\" value=\"${3:value}\"></v-checkbox>$0"),
  ("v-switch\tSwitch component - Vuetify", "v-switch label=\"${1:label}\" v-model=\"${2:value}\"></v-switch>$0"),
  ("v-text-field\tText Field component - Vuetify", "v-text-field\n  name=\"${1:name}\"\n  label=\"${2:label}\"\n  id=\"${3:id}\"\n></v-text-field>$0"),
  ("v-icon\tIcon component - Vuetify", "v-icon>${1:iconName}</v-icon>$0"),
  ("v-list\tList component - Vuetify", "v-list>\n  $1\n</v-list>$0"),
  ("v-list group\tList group component - Vuetify", "v-list-group\n  v-model=\"${1:value}\"\n  v-for=\"${2:item in items}\"\n  :key=\"${3:key}\"\n  :prepend-icon=\"${4:icon}\"\n  no-action\n>\n  $5\n</v-list-group>$0"),
  ("v-list-tile\tList Tile component - Vuetify", "v-list-tile avatar>\n  $1\n</v-list-tile>$0"),
  ("v-list-tile-title\tList Tile Title component - Vuetify", "v-list-tile-title>${1:title}</v-list-tile-title>$0"),
  ("v-list-tile-sub-title\tList Tile Sub Title component - Vuetify", "v-list-tile-sub-title>${1:subTitle}</v-list-tile-sub-title>$0"),
  ("v-list-tile-avatar\tList Tile Avatar component - Vuetify", "v-list-tile-avatar>\n  <img src=\"${1:src}\">\n</v-list-tile-avatar>$0"),
  ("v-list-tile-content\tList Tile Content component - Vuetify", "v-list-tile-content>\n  $1\n</v-list-tile-content>$0"),
  ("v-list-tile-action\tList Tile Action component - Vuetify", "v-list-tile-action>\n  $1\n</v-list-tile-action>$0"),
  ("v-jumbotron\tJumbotron component - Vuetify", "v-jumbotron color=\"${1:primary}\">\n  $2\n</v-jumbotron>$0"),
  ("v-menu\tMenu component - Vuetify", "v-menu ${1:offset-y}>\n  <v-btn color=\"${2:primary}\" ${3:dark} slot=\"activator\">${4:text}</v-btn>\n  <v-list>\n    <v-list-tile v-for=\"${5:item in items}\" :key=\"${6:item.key}\" @click=\"${7:callback}\">\n      <v-list-tile-title>{{ ${8:item.key} }}</v-list-tile-title>\n    </v-list-tile>\n  </v-list>\n</v-menu>$0"),
  ("v-navigation-drawer\tNavigation Drawer component - Vuetify", "v-navigation-drawer>\n  $1\n</v-navigation-drawer>$0"),
  ("v-pagination\tPagination component - Vuetify", "v-pagination :length=\"${1:length}\" v-model=\"${2:page}\"></v-pagination>$0"),
  ("v-parallax\tParallax component - Vuetify", "v-parallax src=\"$1\"></v-parallax>$0"),
  ("v-date-picker\tDate Picker component - Vuetify", "v-date-picker v-model=\"${1:value}\" ${2::landscape=\"true\"} ${3::reactive=\"true\"}></v-date-picker>$0"),
  ("v-time-picker\tTime Picker component - Vuetify", "v-time-picker$1></v-time-picker>$0"),
  ("v-progress-circular\tProgress Circular component - Vuetify", "v-progress-circular :value=\"${1:20}\"></v-progress-circular>$0"),
  ("v-progress-linear\tProgress Linear component - Vuetify", "v-progress-linear ${1::indeterminate=\"true\"}></v-progress-linear>$0"),
  ("v-slider\tSlider component - Vuetify", "v-slider v-model=\"${1:value}\" step=\"${2:0}\"></v-slider>$0"),
  ("v-snackbar\tSnackbar component - Vuetify", "v-snackbar\n  v-model=\"${1:value}\"\n>\n  ${2:snackbarText}\n  <v-btn flat color=\"${3:primary}\" @click.native=\"$1 = false\">Close</v-btn>\n</v-snackbar>$0"),
  ("v-stepper\tStepper component - Vuetify", "v-stepper value=\"${1:1}\">\n  $2\n</v-stepper>$0"),
  ("v-stepper-step\tStepper Step component - Vuetify", "v-stepper-step step=\"${1:1}\">${2:vStepperStepText}</v-stepper-step>$0"),
  ("v-stepper-content\tStepper Content component - Vuetify", "v-stepper-content step=\"${1:1}\">\n  $2\n</v-stepper-content>$0"),
  ("v-stepper-header\tStepper Header component - Vuetify", "v-stepper-header>\n  $1\n</v-stepper-header>$0"),
  ("v-stepper-items\tStepper Items component - Vuetify", "v-stepper-items>\n  $1\n</v-stepper-items>$0"),
  ("v-subheader\tSubheader component - Vuetify", "v-subheader>${1:text}</v-subheader>$0"),
  ("v-tabs\tTabs component - Vuetify", "v-tabs\n  v-model=\"${1:value}\"\n  color=\"${2:primary}\"\n  dark\n  slider-color=\"${3:primary}\"\n>\n  $4\n</v-tabs>$0"),
  ("v-tab\tTab component - Vuetify", "v-tab>\n  $1\n</v-tab>$0"),
  ("v-tabs-items\tTabs Items component - Vuetify", "v-tabs-items>\n  $1\n</v-tabs-items>$0"),
  ("v-tab-item\tTab Item component - Vuetify", "v-tab-item>\n  $1\n</v-tab-item>$0"),
  ("v-tabs-slider\tTabs Slider component - Vuetify", "v-tabs-slider ${1:color=\"${2:primary}\"}></v-tab-item>$0"),
  ("v-toolbar\tToolbar component - Vuetify", "v-toolbar ${1:color=\"${2:primary}\"}>\n  $3\n</v-toolbar>$0"),
  ("v-system-bar\tSystem Bar component - Vuetify", "v-system-bar color=\"${1:primary}\">\n  $2\n</v-system-bar>$0"),
  ("v-tooltip\tTooltip component - Vuetify", "v-tooltip ${1:top}>\n  $2\n</v-tooltip>$0")
]